name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Type of version increment (patch, minor, major)'
        required: true
        default: 'patch'

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # Use PAT instead of GITHUB_TOKEN to checkout
        token: ${{ secrets.PAT_GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install bump2version
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Bump version
      run: |
        bump2version ${{ github.event.inputs.version-type }}
    
    - name: Push changes
      # Use direct push with the PAT
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
      run: |
        # Set the remote URL with the PAT
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        git push
        git push --tags